export const WOOCOMMERCE_API_ERROR = 'WOOCOMMERCE_API_ERROR';
export const WOOCOMMERCE_API_ERROR_CLEAR = 'WOOCOMMERCE_API_ERROR_CLEAR';
export const WOOCOMMERCE_API_PRODUCT_CATEGORIES_GET = 'WOOCOMMERCE_API_PRODUCT_CATEGORIES_GET';
export const WOOCOMMERCE_API_PRODUCT_CATEGORIES_GET_SUCCESS = 'WOOCOMMERCE_API_PRODUCT_CATEGORIES_GET_SUCCESS';
export const WOOCOMMERCE_EDIT_PRODUCT = 'WOOCOMMERCE_EDIT_PRODUCT';
export const WOOCOMMERCE_EDIT_PRODUCT_ATTRIBUTE = 'WOOCOMMERCE_EDIT_PRODUCT_ATTRIBUTE';
export const WOOCOMMERCE_EDIT_PRODUCT_VARIATION = 'WOOCOMMERCE_EDIT_PRODUCT_VARIATION';
